### EXCEPCIONES ###

num1, num2 = 5, 1
num2 = '1'

# Try except
try:
    print (num1 + num2)
    print ('No se ha producido error')
except:
    print ('Se ha producido un error')
    
# Try except else finally

try:
    print (num1 + num2)
    print ('No se ha producido error')
except:
    print ('Se ha producido un error')
else:
    # Se ejecuta si no se produce la excepci贸n
    print ('La ejecuci贸n continua correctamente')
finally:
    # Se ejecuta siempre
    print ('La ejecuci贸n continua ')
    

# Excepci贸n por tipo    
    
try:
    print (num1 + num2)
    print ('No se ha producido error')
except TypeError as error:  # Este bloque se ejecuta solo si es un TypeError
    print (error)

